#!/usr/bin/env bash
# Copyright 2019 releng-tool

base="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

echo 'generate base redirect pages for sub-language folders...'
languages=()
for ref in $(ls -d $base/*/); do
    lang_dir=${ref%%/}
    lang=${lang_dir##*/}
    languages+=($lang)

cat <<EOM >$lang_dir/index.html
<!DOCTYPE html>
<html lang="$lang"><head>
    <meta http-equiv="refresh" content="0; url=https://docs.releng.io/$lang/latest">
</head><body>
<p>You should be redirected automatically; if not, venture to
<a href="https://docs.releng.io/$lang/latest/">/$lang/latest/</a>.</p>
</body></html>
EOM

done

echo 'remove legacy base redirects...'
for ref in $(ls -f $base/*.html); do
    rm ${ref%%/}
done

echo 'build start of sitemap...'
sitemap=$base/sitemap.xml
cat <<EOM >$sitemap
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
EOM

echo 'generating redirect pages for existing latest html landing pages...'
for ref in $(ls -f $base/en/latest/*.html); do
    existing=${ref%%/}
    existing=${existing##*/}
    name=${existing%.*}
    if [ "$name" == 'index' ]; then
        name=''
    fi

cat <<EOM >$base/$existing
<!DOCTYPE html>
<html lang="en"><head>
    <meta http-equiv="refresh" content="2; url=https://docs.releng.io/en/latest">
    <link rel="canonical" href="https://docs.releng.io/$name" />
    <script src="redirect.js"></script>
</head><body>
<p>You should be redirected automatically; if not, venture to
<a href="https://docs.releng.io/en/latest/">/en/latest/</a>.</p>
</body></html>
EOM

    echo '<url>' >>$sitemap
    echo "<loc>https://docs.releng.io/$name</loc>" >>$sitemap
    for lang in "${languages[@]}"; do
        echo "<xhtml:link rel=\"alternate\" hreflang=\"$lang\" href=\"https://docs.releng.io/$lang/latest\"/>" >>$sitemap
    done
    echo '<changefreq>monthly</changefreq>' >>$sitemap
    echo '</url>' >>$sitemap
done

echo 'finalizing sitemap...'
echo '</urlset>' >>$sitemap
